language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run lint
  - npm run test
  - NODE_ENV=production npm run build
branches:
  only:
    - master
    - /^feature-.*/
